/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package server

import kotlin.test.Test

class ServerTest {
  @Test
  fun appHasAGreeting() {
    // val classUnderTest = Server()
    // assertThat(classUnderTest.greeting).isNotNull()
  }
}
