/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package server

class Server {
  val greeting: String
    get() {
      return "Hello World!"
    }
  
}

fun main() {
  println(Server().greeting)
}
