/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.4.1/userguide/multi_project_builds.html
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "server"
include("app")
include("protos")

plugins {
    kotlin("jvm") version "1.9.0" apply false
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
    versionCatalogs {
        create("libs") {
            version("kotlin", "1.9.0")

            version("grpc", "1.57.1")
            library("grpc-stub", "io.grpc", "grpc-stub").versionRef("grpc")
            library("grpc-protobuf", "io.grpc", "grpc-protobuf").versionRef("grpc")
            library("grpc-netty", "io.grpc", "grpc-netty").versionRef("grpc")

            version("grpcKotlin", "1.3.0")
            library("grpc-kotlin-stub", "io.grpc", "grpc-kotlin-stub").versionRef("grpcKotlin")

            bundle("grpc", listOf("grpc-stub", "grpc-protobuf", "grpc-netty", "grpc-kotlin-stub", "grpc-kotlin-stub"))

            version("protobuf", "3.24.0-RC3")
            library("protobuf-java-util", "com.google.protobuf", "protobuf-java-util").versionRef("protobuf")
            library("protobuf-java", "com.google.protobuf", "protobuf-java").versionRef("protobuf")
            library("protobuf-kotlin", "com.google.protobuf", "protobuf-kotlin").versionRef("protobuf")

            bundle("protobuf", listOf("protobuf-java-util", "protobuf-kotlin"))

            version("kotlinx", "1.7.3")
            library("kotlinx-coroutines-core", "org.jetbrains.kotlinx", "kotlinx-coroutines-core").versionRef("kotlinx")

            version("flogger", "0.7.4")
            library("flogger", "com.google.flogger", "flogger").versionRef("flogger")
            library("flogger-backend", "com.google.flogger", "flogger-system-backend").versionRef("flogger")


            bundle("shared", listOf("flogger", "flogger-backend"))

            // Testing specific
            version ("junit", "5.10.0")
            library("junit", "org.junit.jupiter", "junit-jupiter").versionRef("junit")
            library("junit-engine", "org.junit.jupiter", "junit-jupiter-engine").versionRef("junit")

            library("kotlin-test", "org.jetbrains.kotlin", "kotlin-test").version("1.9.0")
            library("truth", "com.google.truth", "truth").version("1.1.5")
             
            bundle("test", listOf("junit", "junit-engine", "kotlin-test", "truth"))

            // Plugins 
            plugin("protobuf", "com.google.protobuf").version("0.9.4")
            plugin("ktfmt", "com.ncorti.ktfmt.gradle" ).version("0.13.0")
        }
    }
}