#! /usr/bin/env bash 
set -e
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )


PATH=$PATH:$SCRIPT_DIR/node_modules/.bin

PROTOC_GEN_TS_PATH="./node_modules/.bin/protoc-gen-ts"

IN_DIR="$SCRIPT_DIR/../server/protos/src/main/proto"  
OUT_DIR="$SCRIPT_DIR/generated"
mkdir -p $OUT_DIR

protoc -I=${IN_DIR} service.proto \
 --plugin="protoc-gen-ts=${PROTOC_GEN_TS_PATH}" \
 --js_out="import_style=commonjs,binary:${OUT_DIR}" \
 --ts_out="service=grpc-web:${OUT_DIR}"